### PR TITLE
Popravi licenco nazaj na originalno Apache-2.0

### PR DESCRIPTION
**Pull request by silverhook**
Licenc, ki so prišle iz povratnega toka (torej od originalnega avtorja/imetnika pravic) se ne prevaja,

Originalna aplikacija je na voljo pod Apache-2.0 licenco, ki je že dolgo časa uveljavljena odprtokodna licenca, in med drugim na [SPDX seznamu pogostih odprtokodnih licenc](https://spdx.org/licenses/Apache-2.0.html).

Ta PR popravi to napako, in besedilo licence spravi nazaj v stanje kot je v originalni aplikaciji: https://github.com/corona-warn-app/cwa-app-android/blob/master/LICENSE

## Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] If this PR comes from a fork, please [Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [ ] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger (closes # 41)
* [ ] [Link your Pull Request to an issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) - Pull Requests that are not linked to an issue with you as an assignee will be closed, except for minor fixes for typos or grammar mistakes in *documentation or code comments*.
* [ ] Create Work In Progress [WIP] pull requests only if you need clarification or an explicit review before you can continue your work item.
* [ ] Make sure that your PR is not introducing _unnecessary_ reformatting (e.g., introduced by on-save hooks in your IDE)
* [ ] Make sure that your PR does not contain changes in text files, therefore the PR must not contain changes in values/strings/* and / or assets/* (see issue #332 for further information)
* [ ] Make sure that your PR does not contain compiled sources (already set by the default .gitignore) and / or binary files

### CODE REVIEW

**Comment by sijanec** [comment]
Heh, a razvijalci vejo, kaj je pull request? (:

Nočem biti pretirano vsiljevalen in nočem vrivati mnenj, ampak samo prvi commit je vseboval več kot eno spremenjeno datoteko.

To lahko nakazuje na to, da so samo uporabljali GitHubove funkcije na spletni strani.

Po mojem mnenju je bil potek razvijanja tak:
* Naredijo Github repozitorij in nekaj readme datotek
* Naložijo si ZIP iz nemške korona aplikacije
* Spremenijo
* Zbrišejo vse datoteke z web editorjem iz githuba, ker ne vejo, kaj je merge.
* ~~Uporabijo funkcijo "Naloži datoteke kot ZIP"~~ Dejansko enkrat uporabijo git client
* Vse nadaljne commite delajo z Web-editorjem

Zakaj drugače bi pred petimi dnevi naredili pet individualnih commitov, velikih zgolj eno datoteko?

Evo, iz git-loga je to očitno. Vsi commiti, razen enega, so narejeni iz Github editorja.

```
cargova@cargova:~/projects[0]$ git clone https://github.com/si-covid-19/ostanizdrav-android ostanizdrav-android-upstream
Cloning into 'ostanizdrav-android-upstream'...
remote: Enumerating objects: 788, done.
remote: Counting objects: 100% (788/788), done.
remote: Compressing objects: 100% (476/476), done.
remote: Total 788 (delta 269), reused 739 (delta 238), pack-reused 0
Receiving objects: 100% (788/788), 2.00 MiB | 3.74 MiB/s, done.
Resolving deltas: 100% (269/269), done.
cargova@cargova:~/projects[0]$ cd ostanizdrav-android-upstream/
cargova@cargova:~/projects/ostanizdrav-android-upstream[0]$ git log
commit 9b7c4c64dd2ac12040e1c7593e5b877bfda5b88d (HEAD -> master, origin/master, origin/HEAD)
Author: mju-di <mju-di@users.noreply.github.com>
Date:   Thu Sep 24 23:26:50 2020 +0200

    Dopolnjena obrazložitev

commit ff14382782bfe35900024a64bd1b66457b3ef9e7
Author: mju-di <mju-di@users.noreply.github.com>
Date:   Thu Sep 24 23:24:05 2020 +0200

    Novi prevodi

commit 753a04209a66f38a78cd40406e0fd4330d2c57ed
Author: mju-di <mju-di@users.noreply.github.com>
Date:   Thu Sep 24 23:21:57 2020 +0200

    Novi prevodi

commit eaf7149b97bdcf8e784dddd38e4e5b3d9fb8287f
Author: mju-di <mju-di@users.noreply.github.com>
Date:   Thu Sep 24 23:19:55 2020 +0200

    Novi prevodi

commit 0f674a156317041a15de68158badef5e4fda342d
Author: mju-di <mju-di@users.noreply.github.com>
Date:   Thu Sep 24 23:05:56 2020 +0200

    Popravki prevodov

commit afa48fb01240362cd843631d1cde980ea7125c0a
Author: mju-di <mju-di@users.noreply.github.com>
Date:   Thu Sep 24 23:02:32 2020 +0200

    Nova verzija

commit 9c71abccf958a7bf0cbe6d85ea4529e3445951eb (tag: v1.1.1)
Author: mju-di <mju-di@users.noreply.github.com>
Date:   Tue Aug 11 22:18:07 2020 +0200

    popravek besedila

commit d26caa9f6c7e29f6dc9a3cf479e12cd885f7f0b7
Author: RSTEAM <info@rsteam.si>
Date:   Tue Aug 11 09:12:26 2020 +0200

    Initial code commit.

commit 7a3d748f4687af0e6026509d7bdb8c7dc2a4f5e5
Author: mju-di <mju-di@users.noreply.github.com>
Date:   Tue Aug 11 09:04:30 2020 +0200

    Delete README.md

commit 60106665e2704790af5ef57ccfaa30e5e5374aff
Author: mju-di <mju-di@users.noreply.github.com>
Date:   Tue Aug 11 09:04:12 2020 +0200

    Delete LICENSE

commit bd8d7e85cdc334d4e15de77544d435370f276ff1
Author: mju-di <mju-di@users.noreply.github.com>
Date:   Tue Aug 11 09:04:01 2020 +0200

    Delete .gitignore

commit 9e5fa20744bacb69e1bf68d244846bbf00ac020c
Author: mju-di <mju-di@users.noreply.github.com>
Date:   Tue Aug 11 08:54:32 2020 +0200

    Create README.md

commit 864b22351562bb40a5f5c735534f266af5c72cd9
Author: mju-di <mju-di@users.noreply.github.com>
Date:   Tue Aug 11 08:53:58 2020 +0200

    Initial commit
```

LP

**Review by marina-rajic — APPROVED** [review]

**Comment by stefanb** [comment]
Izgleda, da je bilo to popravljeno v https://github.com/si-covid-19/ostanizdrav-android/commit/ddb0470b3367b8eedbc0233ae579c241bc993610#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7

Glej https://github.com/si-covid-19/ostanizdrav-android/commits/master/LICENSE

**Comment by silverhook** [comment]
Zgleda tako, @stefanb. Hvala za ping. Zapiram PR/MR.

**Comment by stefanb** [comment]
Važno, da so imeli prevajalci delo 🙃

**Pull request closed without merging**
